name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_windows:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Build
        shell: bash
        run: |
          pip install lxml
          ./build.sh
          pushd dist
          7z a ../Release_windows.zip -tzip -r Pyscripts/
          popd
          ls
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release_windows
          path: Release_windows.zip
  
  release:
    runs-on: ubuntu-latest
    needs: [build_windows]
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Merge built artifacts
        uses: actions/download-artifact@v4
        with:
          name: Release_windows
      - name: Take a look at the files
        run: ls
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            Changes in this Release
          draft: false
          prerelease: false 
          files: |
            Release_windows.zip
  