name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_windows:
    permissions:
      contents: write
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build
        shell: bash
        run: |
          ./build.sh
          7z a Release_windows_console.zip -tzip -r ./dist/Rimtrans_py
          cat build/Rimtrans_py/warn-Rimtrans_py.txt
          ./build.sh --windowed
          7z a Release_windows.zip -tzip -r ./dist/Rimtrans_py
          cat build/Rimtrans_py/warn-Rimtrans_py.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release_windows
          path: |
            Release_windows.zip
            Release_windows_console.zip
  
  release:
    runs-on: ubuntu-latest
    needs: [build_windows]
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Merge built artifacts
        uses: actions/download-artifact@v4
        with:
          name: Release_windows
      - name: Take a look at the files
        run: ls
      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release create ${{ github.ref }} -t "RimTrans_PY ${{ github.ref_name }}" --generate-notes --latest Release_windows.zip Release_windows_console.zip
        
  